ExamVision - Form/ExamVision - Form/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExamVision___Form.Models;
using ExamVision___Form.ModelsView;
using ExamVision___Form.TransferMethod;
using Microsoft.AspNet.Identity;

namespace ExamVision___Form.Controllers
{
    public class FormController : Controller
    {

        // GET: Form
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            ApplicationDbContext db = new ApplicationDbContext();

            var userId = User.Identity.GetUserId();
            var user = db.Users.SingleOrDefault(x => x.Id == userId);
            //Moved to HomeController
            ViewBag.userMail = user.Email;

            return View(db.FormModels.ToList());
        }

        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        // GET: Form/Details/5
        public ActionResult Details(int? id)
        {
            ApplicationDbContext db = new ApplicationDbContext();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormModel formModel = db.FormModels.Find(id);
            if (formModel == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Details", formModel);
        }

        // GET: Form/Create
        //public ActionResult Create()
        //{
        //    ApplicationDbContext db = new ApplicationDbContext();
        //    ViewBag.Cosmo = db.Glasses.SingleOrDefault(x => x.Name == "Cosmo");
        //    ViewBag.Sport = db.Glasses.SingleOrDefault(x => x.Name == "Sport");
        //    ViewBag.Icon = db.Glasses.SingleOrDefault(x => x.Name == "Icon");
        //    ViewBag.Essential = db.Glasses.SingleOrDefault(x => x.Name == "Essential");

        //    return View();
        //}

        // POST: Form/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[Authorize]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(FormModel formModel)
        //{
            
        //    ApplicationDbContext db = new ApplicationDbContext();

        //    formModel.ImportDate = DateTime.Now;
        //    if (ModelState.IsValid)
        //    {
        //        db.FormModels.Add(formModel);
        //        db.SaveChanges();
        //        return RedirectToAction("EditConfirmation");
        //    }

        //    return View(formModel);
        //}

        // GET: Form/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            ApplicationDbContext db = new ApplicationDbContext();

            ViewBag.Cosmo = db.Glasses.SingleOrDefault(x => x.Name == "Cosmo");
            ViewBag.Sport = db.Glasses.SingleOrDefault(x => x.Name == "Sport");
            ViewBag.Icon = db.Glasses.SingleOrDefault(x => x.Name == "Icon");
            ViewBag.Essential = db.Glasses.SingleOrDefault(x => x.Name == "Essential");

            var userId = User.Identity.GetUserId();
            var user = db.Users.SingleOrDefault(x => x.Id == userId);
            ViewBag.userMail = user.Email;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //FormModel formModel = db.FormModels.Find(id);
            FormViewModel model = new FormViewModel();
            model.Form = db.FormModels.SingleOrDefault(x => x.ID == id);
            if (model.Form == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: Form/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FormViewModel formModel)
        {
            ApplicationDbContext db = new ApplicationDbContext();

            if (ModelState.IsValid)
            {
                if (formModel.Form.isOrdered == false)
                {
                    // uploaded file
                    if (formModel.UploadedFile != null && formModel.UploadedFile.ContentLength > 0)
                    {
                        // Remove old picture
                        try
                        {
                            System.IO.File.Delete(formModel.Form.picture_upload_data_field);
                        }
                        catch (Exception)
                        {

                        }
                        string directory = Server.MapPath("~/Content/ClientPics/");
                        string filename = "ClientImg_" + formModel.Form.ID +
                                          Path.GetExtension(formModel.UploadedFile.FileName);
                        var path = Path.Combine(directory, filename);

                        if (!Directory.Exists(directory))
                            Directory.CreateDirectory(directory);

                        formModel.UploadedFile.SaveAs(path);
                        formModel.Form.picture_upload_data_field = "/Content/ClientPics/" + filename;
                    }
                    // Save
                    db.FormModels.AddOrUpdate(formModel.Form);
                    db.SaveChanges();
                }
                return RedirectToAction("EditConfirmation", new {id = formModel.Form.ID});
            }
            return View(formModel);
        }

       
        public ActionResult EditConfirmation(int? id)
        {
            ApplicationDbContext db = new ApplicationDbContext();

            FormModel model = db.FormModels.SingleOrDefault(x => x.ID == id);
            return View(model);
        }


        // GET: Form/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            ApplicationDbContext db = new ApplicationDbContext();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormModel formModel = db.FormModels.Find(id);
            if (formModel == null)
            {
                return HttpNotFound();
            }
            return View(formModel);
        }

        // POST: Form/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            ApplicationDbContext db = new ApplicationDbContext();

            FormModel formModel = db.FormModels.Find(id);
            if (formModel.isOrdered == false)
            {
                db.FormModels.Remove(formModel);
                db.SaveChanges();
            }
            return RedirectToAction("UserPanel", "Admin");
        }

        protected override void Dispose(bool disposing)
        {
            ApplicationDbContext db = new ApplicationDbContext();

            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult OrderCompletion(int? id)
        {
            ApplicationDbContext db = new ApplicationDbContext();

            FormModel form = db.FormModels.Find(id);
            

            //Donez by le tvede
            //Aktiver det her 
            var mysqlServer = new MysqlContext();
            mysqlServer.Database.CreateIfNotExists();
            mysqlServer.SaveChanges();
            var exportModel = TransferConverter.Convert(form);
            mysqlServer.test_orders.Add(exportModel);
            mysqlServer.SaveChanges();

            form.isOrdered = true;
            db.SaveChanges();


            return RedirectToAction("UserPanel","Admin");
        }
    }
}

ExamVision - Form/ExamVision - Form/Views/Form/Delete.cshtml
@model ExamVision___Form.Models.FormModel

@{
    ViewBag.Title = "Delete";
}
<div class="row">
    <h1>Delete</h1>
    <div class="row">
        <div class="col-md-offset-1"></div>
        <div class="col-md-10">
            <h3>Are you sure you want to delete this?</h3>

            <div>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "UserPanel", "Admin")
                    </div>
                }
            </div>
        </div>
    </div>
</div>

ExamVision - Form/ExamVision - Form/Views/Form/Edit.cshtml
@model ExamVision___Form.ModelsView.FormViewModel

@{
    ViewBag.Title = "ExamVision - The Form";
}

<div class="" id="formSite">
    @using (Html.BeginForm("Edit", "Form", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            <div class="text-danger">@Html.ValidationSummary()</div>
        </div>
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Form.ID)
        @Html.HiddenFor(x => x.Form.ImportDate)

        @Html.Partial("_FormIndex", Model)

        <div id="submitButton" class="row container-fluid formBlock">
            <div class="col-lg-2">
                <input class="btn btn-success" type="Submit" value="Save" />
            </div>
        </div>

    }
</div>

<script>
    //$("#frameSelector").click();
    //$("#frameSelector").click();
</script>

ExamVision - Form/ExamVision - Form/Views/Form/EditConfirmation.cshtml
@model ExamVision___Form.Models.FormModel


@*@{
    ViewBag.Title = "Edit Confirmation";
}*@

<style>
    #orderCompInfo {
        padding-top: 2%;
        padding-bottom: 1.5%;
    }

    .orderCompChoice {
        padding: 8% 5% 20% 5%;
        max-height: 450px;
        background-color: #eee;
        border: 1px solid white;
    }

        .orderCompChoice:hover {
            background-color: #F7F7F7;
        }

        .orderCompChoice h2 {
            padding-bottom: 2%;
        }
</style>
<div class="row">
    <div class="col-xs-12 text-sm-center" id="orderCompInfo">
        <h1 class="spacerBot spacerTop">Your order is now SAVED, but NOT COMPLETED and NOT yet sent to ExamVision</h1>
        <h6 class="spacerTop">
            <span style="font-size: 120%">You have now saved your order.  This order can be found as a SAVED order in Order view.<br />
            To CONFIRM your ORDER please click COMPLETE ORDER below.</span>
        </h6>
    </div>
</div>
<div class="row">
    <div class="col-lg-6 orderCompChoice text-sm-center">
        <h2>Go to order overview</h2>
        <p>Here you will find the Order view, where you have a total overview of all your orders: <br /> <strong>SAVED</strong> (<em>not completed</em>) orders and <strong>CONFIRMED</strong> orders.</p>
        <button type="button" class="btn btn-warning center-block spacerBot spacerTop" onclick="location.href = '@Url.Action("UserPanel", "Admin")'">Order view</button>
    </div>
    <div class="col-lg-6 orderCompChoice  text-sm-center">
        <h2>Would you like to complete the order?</h2>
        <em><strong>This will send your order to ExamVision. </strong></em>
        <p><strong>Please note: </strong>When you have confirmed your order you cannot go back to edit the information. </p>
        <p>You’ll find the <span style="text-decoration: underline;">Order Confirmation</span> at <span style="text-decoration: underline;">Order view</span> under COMPLETED ORDERS, saved by Client Name.</p>
        <button type="button" class="btn btn-success center-block spacerBot spacerTop"
                onclick="location.href = '@Url.Action("OrderCompletion", new {id = Model.ID})'">
            Complete order
        </button>
        <em class="spacerBot spacerTop">(Order confirmations will no longer be sent via email)</em>
    </div>
</div>